DefPrefix{
  open = { '<leader>o', desc = '[O]pen' },
  new = { '<leader>n', desc = '[N]ew' },
  open_vim = { '<leader>ov', desc = '[V]im config' },
  code = { '<leader>d', desc = 'LSP' },
  -- note = { '<leader>n', desc = '[N]otes' },
  speed_dial = { '<leader>s', desc = '[S]peed dial' },
  vim = { '<leader>v', desc = '[V]im' },
  quickfix = { '<leader>q', desc = '[Q]uickfix' },
  terminal = { '<leader>t', desc = '[T]erminal' },
  terminal_execute = { '<leader>te', desc = 'Terminal [e]xecute' },
  context = { '<leader>c', desc = '[C]ontext' },
  -- git = { '<leader>g', desc = '[G]it' },
}

DefKeymap{
  vim_kill_buffers = { 'k', prefix = 'vim', mode = { 'n' }, desc = '[K]ill buffers' },
  vim_delete_buffer = { 'd', prefix = 'vim', mode = { 'n' }, desc = '[D]elete buffer' },
  vim_only_buffer = { 'o', prefix = 'vim', mode = { 'n' }, desc = '[O]nly buffer' },
  vim_wrap = { 'w', prefix = 'vim', mode = { 'n' }, desc = '[W]rap lines' },
  vim_number_line = { 'n', prefix = 'vim', mode = { 'n' }, desc = '[N]umber line' },
  vim_relative_number_line = { 'r', prefix = 'vim', mode = { 'n' }, desc = '[R]elative number line' },
  vim_previous_buffer = { 'v', prefix = 'vim', mode = { 'n' }, desc = 'Previous buffer' },
  vim_msdos_remover = { '<leader>m', mode = { 'n' }, desc = '[M]S-DOS remover' },
  select_last_paste = { '<leader>p', mode = { 'n' }, desc = 'Select last [p]aste' },
  clear = { '<c-c>', mode = { 'n' }, desc = '[C]lear session' },
  write_file = { '<c-s>', mode = { 'n', 'x', 'o', 'i' }, desc = '[W]rite' },
  jump = { 's', mode = { 'n', 'x', 'o' }, desc = 'Jump' },
  jump_treesitter = { 'S', mode = { 'n', 'x', 'o' }, desc = 'Treesitter jump' },
  open_file_browser = { 'o', prefix = 'open', mode = { 'n' }, desc = 'Explore current directory' },
  open_project_browser = { 'p', prefix = 'open', mode = { 'n' }, desc = 'Explore current [p]roject' },
  open_persistent_file_browser = { 'O', prefix = 'open', mode = { 'n' }, desc = 'Persistent explorer' },
  open_home = { 'h', prefix = 'open', mode = { 'n' }, desc = 'Explore [h]ome' },
  open_dev = { 'd', prefix = 'open', mode = { 'n' }, desc = 'Explore [d]ev' },
  open_root = { '/', prefix = 'open', mode = { 'n' }, desc = 'Explore root' },
  open_temp = { 't', prefix = 'open', mode = { 'n' }, desc = 'Explore [t]mp' },
  open_config = { 'C', prefix = 'open', mode = { 'n' }, desc = 'Explore config' },
  fuzzy_config = { 'c', prefix = 'open', mode = { 'n' }, desc = 'Fuzzy [c]onfig' },
  open_config_vim_autocmds = { 'a', prefix = 'open_vim', mode = { 'n' }, desc = 'Open nvim/[a]utocmds.lua' },
  open_config_vim_context = { 'C', prefix = 'open_vim', mode = { 'n' }, desc = 'Explore ~/.[c]ontext/nvim' },
  fuzzy_vim_context = { 'c', prefix = 'open_vim', mode = { 'n' }, desc = 'Fuzzy ~/.[c]ontext/nvim' },
  open_config_vim_init = { 'i', prefix = 'open_vim', mode = { 'n' }, desc = 'Open nvim/[i]nit.lua' },
  open_config_vim_keymaps = { 'k', prefix = 'open_vim', mode = { 'n' }, desc = 'Open nvim/[k]eymaps.lua' },
  open_config_vim_modules = { 'M', prefix = 'open_vim', mode = { 'n' }, desc = 'Explore nvim/[m]odules' },
  fuzzy_vim_modules = { 'm', prefix = 'open_vim', mode = { 'n' }, desc = 'Fuzzy nvim/[m]odules' },
  open_config_vim_api = { '`', prefix = 'open_vim', mode = { 'n' }, desc = 'Open nvim/api.lua' },
  fuzzy_files = { '<leader>f', mode = { 'n' }, desc = 'Fuzzy files' },
  fuzzy_symbols = { 's', prefix = 'code', mode = { 'n' }, desc = 'Fuzzy [s]ymbols' },
  fuzzy_references = { 'r', prefix = 'code', mode = { 'n' }, desc = 'Fuzzy [r]eferences' },
  fuzzy_diagnostics = { 'z', prefix = 'code', mode = { 'n' }, desc = 'Fuzzy diagnostics' },
  fuzzy_workspace_diagnostics = { 'Z', prefix = 'code', mode = { 'n' }, desc = 'Fuzzy project diagnostics' },
  fuzzy_code_actions = { 'a', prefix = 'code', mode = { 'n' }, desc = 'Fuzzy code [a]ctions' },
  fuzzy_live_grep = { '<leader>/', mode = { 'n' }, desc = 'Fuzzy project grep' },
  fuzzy_grep = { '<leader><space>', mode = { 'n' }, desc = 'Fuzzy grep' },
  fuzzy_help = { '<leader>?', mode = { 'n' }, desc = 'Fuzzy help' },
  fuzzy_buffers = { '<leader>k', mode = { 'n' }, desc = 'Fuzzy buffers' },
  fuzzy_command_history = { '<leader>h', mode = { 'n' }, desc = 'Fuzzy command [h]istory' },
  fuzzy_color_schemes = { 'c', prefix = 'vim', mode = { 'n' }, desc = 'Fuzzy [c]olor schemes' },
  toggle_auto_comments = { '<leader>A', mode = { 'n' }, desc = 'Toggle auto-comment' },
  smart_comma = { '<m-,>', mode = { 'i' }, desc = 'Context-aware comma insertion' },
  goto_definition = { 'd', prefix = 'code', mode = { 'n' }, desc = 'Goto [d]efinition' },
  goto_type_definition = { 't', prefix = 'code', mode = { 'n' }, desc = 'Goto [t]ype definition' },
  goto_implementation = { 'i', prefix = 'code', mode = { 'n' }, desc = 'Goto [i]mplementation' },
  rename = { '<leader>r', mode = { 'n' }, desc = 'Rename symbol' },
  show_diagnostics = { '<leader>z', mode = { 'n' }, desc = 'Diagnostics under cursor' },
  -- code_actions = { '<leader>a', mode = { 'n' }, desc = 'Show code [a]ctions' },
  -- code_actions_range = { '<leader>a', mode = { 'v' }, desc = 'Show code [a]ctions' },
  speed_dial_add = { 'a', prefix = 'speed_dial', mode = { 'n' }, desc = '[A]dd to speed dial' },
  speed_dial_select = { 's', prefix = 'speed_dial', mode = { 'n' }, desc = '[S]elect from speed dial' },
  speed_dial_1 = { '<leader>1', mode = { 'n' }, desc = 'Speed dial [1]' },
  speed_dial_2 = { '<leader>2', mode = { 'n' }, desc = 'Speed dial [2]' },
  speed_dial_3 = { '<leader>3', mode = { 'n' }, desc = 'Speed dial [3]' },
  speed_dial_4 = { '<leader>4', mode = { 'n' }, desc = 'Speed dial [4]' },
  speed_dial_5 = { '<leader>5', mode = { 'n' }, desc = 'Speed dial [5]' },
  speed_dial_prev = { 'p', prefix = 'speed_dial', mode = { 'n' }, desc = '[P]revious speed dial' },
  speed_dial_next = { 'n', prefix = 'speed_dial', mode = { 'n' }, desc = '[N]ext speed dial' },
  speed_dial_clear = { 'c', prefix = 'speed_dial', mode = { 'n' }, desc = '[C]lear speed dial' },
  splitjoin = { '<leader>j', mode = { 'n' }, desc = 'Split[j]oin' },
  -- note_agenda = { 'a', prefix = 'note', mode = { 'n' }, desc = 'Notes [a]genda' },
  -- note_todo = { 't', prefix = 'note', mode = { 'n' }, desc = 'Notes [t]odo' },
  -- note_capture = { 'c', prefix = 'note', mode = { 'n' }, desc = 'Notes [c]apture' },
  -- note_fuzzy = { 'n', prefix = 'note', mode = { 'n' }, desc = 'Notes fuzzy' },
  -- note_explore = { 'N', prefix = 'note', mode = { 'n' }, desc = 'Notes explore' },
  -- note_inbox = { 'i', prefix = 'note', mode = { 'n' }, desc = 'Notes [i]nbox' },
  -- note_normal_insert = { '<m-n>', mode = { 'n' }, desc = 'Notes insert' },
  -- note_insert = { '<m-n>', mode = { 'i' }, desc = 'Notes insert' },
  -- note_todo_change = { ';', prefix = 'note', mode = { 'n' }, desc = 'Notes todo change' },
  -- note_refile = { 'r', prefix = 'note', mode = { 'n' }, desc = 'Notes [r]efile' },
  -- note_schedule = { 's', prefix = 'note', mode = { 'n' }, desc = 'Notes [s]chedule' },
  -- note_promote = { 'p', prefix = 'note', mode = { 'n' }, desc = 'Notes [p]romote' },
  -- note_demote = { 'd', prefix = 'note', mode = { 'n' }, desc = 'Notes [d]emote' },
  -- note_headings = { 'h', prefix = 'note', mode = { 'n' }, desc = 'Notes [h]eadings' },
  scratchpad = { '<leader>;', mode = { 'n' }, desc = 'Toggle scratchpad' },
  toggle_diagnostics = { '<leader>Z', mode = { 'n' }, desc = 'Toggle diagnostics' },
  lsp_info = { '<leader>i', mode = { 'n' }, desc = '[I]nfo under cursor' },
  reload_file = { '<leader>R', mode = { 'n' }, desc = 'Reload file' },
  black_hole_delete = { '<leader>x', mode = { 'x' }, desc = 'Black hole delete' },
  black_hole_paste = { '<leader>p', mode = { 'x' }, desc = 'Black hole [p]aste' },
  toggle_eol_comma = { '<f14>', mode = { 'n', 'i' }, desc = 'Toggle EOL comma' },
  toggle_eol_period = { '<f15>', mode = { 'n', 'i' }, desc = 'Toggle EOL period' },
  toggle_eol_semicolon = { '<f16>', mode = { 'n', 'i' }, desc = 'Toggle EOL semicolon' },
  empty_file = { 'n', prefix = 'new', mode = { 'n' }, desc = 'Text file' },
  empty_json_file = { 'j', prefix = 'new', mode = { 'n' }, desc = '[J]SON file' },
  empty_lua_file = { 'l', prefix = 'new', mode = { 'n' }, desc = '[L]ua file' },
  empty_vim_file = { 'v', prefix = 'new', mode = { 'n' }, desc = '[V]im file' },
  qf_toggle = { 'q', prefix = 'quickfix', mode = { 'n' }, desc = 'Quickfix [t]oggle' },
  qf_next = { 'n', prefix = 'quickfix', mode = { 'n' }, desc = 'Quickfix [n]ext' },
  qf_previous = { 'p', prefix = 'quickfix', mode = { 'n' }, desc = 'Quickfix [p]revious' },
  qf_first = { 'f', prefix = 'quickfix', mode = { 'n' }, desc = 'Quickfix [f]irst' },
  qf_last = { 'l', prefix = 'quickfix', mode = { 'n' }, desc = 'Quickfix [l]ast' },
  qf_add = { 'a', prefix = 'quickfix', mode = { 'n' }, desc = 'Quickfix [a]dd' },
  qf_open = { 'o', prefix = 'quickfix', mode = { 'n' }, desc = 'Quickfix [o]pen' },
  qf_close = { 'c', prefix = 'quickfix', mode = { 'n' }, desc = 'Quickfix [c]lose' },
  qf_clear = { 'x', prefix = 'quickfix', mode = { 'n' }, desc = 'Quickfix clear' },
  qf_go = { 'g', prefix = 'quickfix', mode = { 'n' }, desc = 'Quickfix [g]o' },
  qf_diagnostics = { 'z', prefix = 'quickfix', mode = { 'n' }, desc = 'Quickfix diagnostics' },
  qf_all_diagnostics = { 'Z', prefix = 'quickfix', mode = { 'n' }, desc = 'Quickfix all diagnostics' },
  qf_delete = { 'd', prefix = 'quickfix', mode = { 'n' }, desc = 'Quickfix [d]elete' },
  terminal_add = { 'a', prefix = 'terminal', mode = { 'n' }, desc = 'Terminal [a]dd' },
  terminal_rename = { 'r', prefix = 'terminal', mode = { 'n' }, desc = 'Terminal [r]ename' },
  terminal_quickadd = { 'q', prefix = 'terminal', mode = { 'n' }, desc = 'Terminal [q]uickadd' },
  terminal_switch = { 't', prefix = 'terminal', mode = { 'n' }, desc = 'Terminal switch' },
  -- terminal_list = { 'l', prefix = 'terminal', mode = { 'n' }, desc = 'Terminal [l]ist' },
  terminal_1 = { '1', prefix = 'terminal', mode = { 'n' }, desc = 'Terminal [1]' },
  terminal_2 = { '2', prefix = 'terminal', mode = { 'n' }, desc = 'Terminal [2]' },
  terminal_3 = { '3', prefix = 'terminal', mode = { 'n' }, desc = 'Terminal [3]' },
  terminal_4 = { '4', prefix = 'terminal', mode = { 'n' }, desc = 'Terminal [4]' },
  terminal_5 = { '5', prefix = 'terminal', mode = { 'n' }, desc = 'Terminal [5]' },
  terminal_execute_1 = { '1', prefix = 'terminal_execute', mode = { 'n' }, desc = 'Terminal [1] execute' },
  terminal_execute_2 = { '2', prefix = 'terminal_execute', mode = { 'n' }, desc = 'Terminal [2] execute' },
  terminal_execute_3 = { '3', prefix = 'terminal_execute', mode = { 'n' }, desc = 'Terminal [3] execute' },
  terminal_execute_4 = { '4', prefix = 'terminal_execute', mode = { 'n' }, desc = 'Terminal [4] execute' },
  terminal_execute_5 = { '5', prefix = 'terminal_execute', mode = { 'n' }, desc = 'Terminal [5] execute' },
  terminal_execute_last = { 'e', prefix = 'terminal_execute', mode = { 'n' }, desc = 'Terminal [e]xecute' },
  terminal_detach = { '<f16>', mode = { 't' }, desc = 'Terminal detach' },
  terminal_cancel = { 'c', prefix = 'terminal', mode = { 'n' }, desc = 'Terminal [c]ancel' },
  open_idea = { 'i', prefix = 'open', mode = { 'n' }, desc = 'Open in [I]DEA' },
  -- open_rider = { 'r', prefix = 'open', mode = { 'n' }, desc = 'Open in [R]ider' },
  undotree = { '<leader>u', mode = { 'n' }, desc = '[U]ndo tree' },
}

