DefPrefix{
open = { '<leader>o', desc = '[o]pen' },
  open_new = { '<leader>on', desc = '[n]ew' },
  open_vim = { '<leader>ov', desc = 'n[v]im config' },
  code = { '<leader>d', desc = 'LSP' },
  -- note = { '<leader>n', desc = '[n]otes' },
  -- note_bookmark = { '<leader>ns', desc = '[n]otes save bookmark' },
  -- note_del_bookmark = { '<leader>nx', desc = '[n]otes delete bookmark' },
  speed_dial = { '<leader>s', desc = '[s]peed dial' },
  vim = { '<leader>v', desc = '[v]im' },
  vim_tabs = { '<leader>v;', desc = 'tabs' },
  quickfix = { '<leader>q', desc = '[q]uickfix' },
  terminal = { '<leader>t', desc = '[t]erminal' },
  terminal_execute = { '<leader>te', desc = 'terminal [e]xecute' },
  context = { '<leader>c', desc = '[c]ontext' },
  edit = { '<leader>e', desc = '[e]dit' },
  yank = { '<leader>y', desc = '[y]ank' },
  ai = { '<leader>a', desc = 'AI' },
  -- git = { '<leader>g', desc = '[g]it' },
}

DefKeymap{
  vim_quick_delete = { '<m-x>', mode = { 'n' }, desc = 'quick delete line' },
  select_last_insert = { '<leader>i', mode = { 'n' }, desc = 'select last [i]nsert' },
  select_last_paste = { '<leader>p', mode = { 'n' }, desc = 'select last [p]aste' },
  cd_into = { '<leader>W', mode = { 'n' }, desc = 'set current directory' },
  select_between_space = { '<m-i>', mode = { 'n', 'x', 'o' }, desc = 'select [i]nside spaces' },
  select_all = { '<m-w>', mode = { 'n', 'x', 'o' }, desc = 'select [w]hole buffer' },
  cancel = { '<c-c>', mode = { 'n', 'x', 'o', 'i' }, desc = 'cancel' },
  soft_cancel = { '<m-c>', mode = { 'n', 'x', 'o', 'i' }, desc = 'soft cancel' },
  write_file = { '<c-s>', mode = { 'n', 'x', 'o', 'i' }, desc = '[W]rite' },
  jump = { 's', mode = { 'n', 'x', 'o' }, desc = 'jump' },
  jump_treesitter = { 'S', mode = { 'n', 'x', 'o' }, desc = 'treesitter jump' },
  search_files = { '<leader>f', mode = { 'n' }, desc = 'search [f]iles' },
  search_live_grep = { '<leader>/', mode = { 'n' }, desc = 'grep project' },
  search_grep = { '<leader><space>', mode = { 'n' }, desc = 'grep file' },
  search_help = { '<leader>?', mode = { 'n' }, desc = 'search help' },
  search_man = { '<leader>M', mode = { 'n' }, desc = 'search man pages' },
  search_buffers = { '<leader>k', mode = { 'n' }, desc = 'search buffers' },
  search_command_history = { '<leader>h', mode = { 'n' }, desc = 'search command [h]istory' },
  search_oldfiles = { '<leader>j', mode = { 'n' }, desc = 'search oldfiles' },
  rename = { '<leader>r', mode = { 'n' }, desc = 'rename symbol' },
  show_diagnostics = { '<leader>z', mode = { 'n' }, desc = 'diagnostics under cursor' },
  -- code_actions = { '<leader>a', mode = { 'n' }, desc = 'show code [a]ctions' },
  -- code_actions_range = { '<leader>a', mode = { 'v' }, desc = 'show code [a]ctions' },
  speed_dial_1 = { '<leader>1', mode = { 'n' }, desc = 'speed dial [1]' },
  speed_dial_2 = { '<leader>2', mode = { 'n' }, desc = 'speed dial [2]' },
  speed_dial_3 = { '<leader>3', mode = { 'n' }, desc = 'speed dial [3]' },
  speed_dial_4 = { '<leader>4', mode = { 'n' }, desc = 'speed dial [4]' },
  speed_dial_5 = { '<leader>5', mode = { 'n' }, desc = 'speed dial [5]' },
  split = { 'gj', mode = { 'n', 'v' }, desc = 'Split' },
  join = { 'gk', mode = { 'n', 'v' }, desc = 'Join' },
  scratchpad = { '<leader>;', mode = { 'n' }, desc = 'toggle scratchpad' },
  scratchpad_current_buffer = { '<leader>:', mode = { 'n' }, desc = 'open scratchpad' },
  toggle_diagnostics = { '<leader>Z', mode = { 'n' }, desc = 'toggle diagnostics' },
  reload_file = { '<leader>R', mode = { 'n' }, desc = '[R]eload file' },
  black_hole_delete = { '<leader>x', mode = { 'x' }, desc = 'black hole delete' },
  black_hole_paste = { '<leader>p', mode = { 'x' }, desc = 'black hole [p]aste' },
  toggle_eol_comma = { '<m-,>', mode = { 'n', 'i' }, desc = 'toggle EOL comma' },
  toggle_eol_semicolon = { '<m-;>', mode = { 'n', 'i' }, desc = 'toggle EOL semicolon' },
  undotree = { '<leader>u', mode = { 'n' }, desc = '[u]ndo tree' },
  goto_mark = { '<leader>m', mode = { 'n' }, desc = 'goto [m]ark' },
  delete_forward = { '<c-l>', mode = { 'i' }, desc = 'delete forward' },
  workspaces_select = { '<leader>w', mode = { 'n' }, desc = '[w]orkspaces' },
  window_left = { '<m-h>', mode = { 'n' }, desc = 'window left' },
  window_down = { '<m-j>', mode = { 'n' }, desc = 'window down' },
  window_up = { '<m-k>', mode = { 'n' }, desc = 'window up' },
  window_right = { '<m-l>', mode = { 'n' }, desc = 'window right' },
  redirect = { '<c-q>', mode = { 'n' }, desc = 'redirect messages' },
  toggle_completions = { '<f1>', mode = { 'n', 'x', 'o', 'c', 'i' }, desc = 'toggle completions' },
  toggle_lsp = { '<f2>', mode = { 'n', 'x', 'o', 'c', 'i' }, desc = 'toggle lsp' },
  smart_center = { 'zZ', mode = { 'n' }, desc = 'smart center' },
  ai_chat = { 'a', prefix = 'ai', mode = { 'n' }, desc = 'Toggle chat' },
  ai_inline = { 'i', prefix = 'ai', mode = { 'n' }, desc = '[i]nline prompt' },
  goto_definition = { 'd', prefix = 'code', mode = { 'n' }, desc = 'goto [d]efinition' },
  goto_implementation = { 'i', prefix = 'code', mode = { 'n' }, desc = 'goto [i]mplementation' },
  goto_type_definition = { 't', prefix = 'code', mode = { 'n' }, desc = 'goto [t]ype definition' },
  search_references = { 'r', prefix = 'code', mode = { 'n' }, desc = 'search [r]eferences' },
  search_symbols = { 's', prefix = 'code', mode = { 'n' }, desc = 'search [s]ymbols' },
  search_code_actions = { 'a', prefix = 'code', mode = { 'n' }, desc = 'search code [a]ctions' },
  search_diagnostics = { 'z', prefix = 'code', mode = { 'n' }, desc = 'search diagnostics' },
  search_workspace_diagnostics = { 'Z', prefix = 'code', mode = { 'n' }, desc = 'search project diagnostics' },
  toggle_outline = { 'o', prefix = 'code', mode = { 'n' }, desc = 'toggle [o]utline' },
  indent_all = { 'I', prefix = 'edit', mode = { 'n' }, desc = '[I]ndent all' },
  msdos_remover = { 'm', prefix = 'edit', mode = { 'n' }, desc = '[M]S-DOS remover' },
  revert_buffer = { 'R', prefix = 'edit', mode = { 'n' }, desc = '[R]evert_buffer' },
  nuke = { 'n', prefix = 'edit', mode = { 'n' }, desc = '[n]uke file' },
  replace = { 'r', prefix = 'edit', mode = { 'n' }, desc = '[r]eplace' },
  delete_above = { 'K', prefix = 'edit', mode = { 'n' }, desc = 'delete above' },
  delete_below = { 'J', prefix = 'edit', mode = { 'n' }, desc = 'delete below' },
  fix_whitespace = { 'w', prefix = 'edit', mode = { 'n' }, desc = 'fix [w]hitespace' },
  insert_date = { 'd', prefix = 'edit', mode = { 'n' }, desc = 'insert [d]ate' },
  insert_blank_above = { 'k', prefix = 'edit', mode = { 'n' }, desc = 'insert blank line above' },
  insert_blank_below = { 'j', prefix = 'edit', mode = { 'n' }, desc = 'insert blank line below' },
  remove_empty_lines = { 'e', prefix = 'edit', mode = { 'n' }, desc = 'remove [e]mpty lines' },
  single_empty_line = { 'E', prefix = 'edit', mode = { 'n' }, desc = 'single empty line' },
  indent_line = { 'i', prefix = 'edit', mode = { 'n', 'x' }, desc = '[i]ndent' },
  -- notes_explore = { 'F', prefix = 'note', mode = { 'n' }, desc = 'notes explore' },
  -- notes_search = { 'f', prefix = 'note', mode = { 'n' }, desc = 'notes [f]ind' },
  -- notes_add = { 'a', prefix = 'note', mode = { 'n' }, desc = 'notes [a]dd' },
  -- notes_undo = { 'u', prefix = 'note', mode = { 'n' }, desc = 'notes [u]ndo' },
  -- notes_inbox = { 'i', prefix = 'note', mode = { 'n' }, desc = 'notes [i]nbox' },
  -- notes_toc = { 'c', prefix = 'note', mode = { 'n' }, desc = 'notes table of [c]ontents' },
  -- notes_toggle = { 'n', prefix = 'note', mode = { 'n' }, desc = 'notes toggle' },
  -- notes_grep = { '/', prefix = 'note', mode = { 'n' }, desc = 'notes grep' },
  -- notes_goto_bookmark_1 = { '1', prefix = 'note', mode = { 'n' }, desc = 'notes [1]' },
  -- notes_goto_bookmark_2 = { '2', prefix = 'note', mode = { 'n' }, desc = 'notes [2]' },
  -- notes_goto_bookmark_3 = { '3', prefix = 'note', mode = { 'n' }, desc = 'notes [3]' },
  -- notes_goto_bookmark_4 = { '4', prefix = 'note', mode = { 'n' }, desc = 'notes [4]' },
  -- notes_goto_bookmark_5 = { '5', prefix = 'note', mode = { 'n' }, desc = 'notes [5]' },
  -- notes_bookmark_1 = { '1', prefix = 'note_bookmark', mode = { 'n' }, desc = 'notes bookmark [1]' },
  -- notes_bookmark_2 = { '2', prefix = 'note_bookmark', mode = { 'n' }, desc = 'notes bookmark [2]' },
  -- notes_bookmark_3 = { '3', prefix = 'note_bookmark', mode = { 'n' }, desc = 'notes bookmark [3]' },
  -- notes_bookmark_4 = { '4', prefix = 'note_bookmark', mode = { 'n' }, desc = 'notes bookmark [4]' },
  -- notes_bookmark_5 = { '5', prefix = 'note_bookmark', mode = { 'n' }, desc = 'notes bookmark [5]' },
  -- notes_delete_bookmark_1 = { '1', prefix = 'note_del_bookmark', mode = { 'n' }, desc = 'notes delete bookmark [1]' },
  -- notes_delete_bookmark_2 = { '2', prefix = 'note_del_bookmark', mode = { 'n' }, desc = 'notes delete bookmark [2]' },
  -- notes_delete_bookmark_3 = { '3', prefix = 'note_del_bookmark', mode = { 'n' }, desc = 'notes delete bookmark [3]' },
  -- notes_delete_bookmark_4 = { '4', prefix = 'note_del_bookmark', mode = { 'n' }, desc = 'notes delete bookmark [4]' },
  -- notes_delete_bookmark_5 = { '5', prefix = 'note_del_bookmark', mode = { 'n' }, desc = 'notes delete bookmark [5]' },
  -- notes_bookmarks = { 'l', prefix = 'note', mode = { 'n' }, desc = 'notes [l]ist bookmarks' },
  -- open_context = { 'C', prefix = 'open', mode = { 'n' }, desc = 'explore [c]ontext' },
  open_dev_browser = { 'd', prefix = 'open', mode = { 'n' }, desc = 'explore [d]ev' },
  open_home_browser = { 'h', prefix = 'open', mode = { 'n' }, desc = 'explore [h]ome' },
  open_temp_browser = { 't', prefix = 'open', mode = { 'n' }, desc = 'explore [t]mp' },
  open_config_browser = { 'A', prefix = 'open', mode = { 'n' }, desc = 'explore all configs' },
  open_project_browser = { 'p', prefix = 'open', mode = { 'n' }, desc = 'explore current [p]roject' },
  open_file_browser = { 'o', prefix = 'open', mode = { 'n' }, desc = 'explore current directory' },
  open_root_browser = { '/', prefix = 'open', mode = { 'n' }, desc = 'explore root' },
  -- search_context = { 'c', prefix = 'open', mode = { 'n' }, desc = 'open [c]ontext' },
  open_idea = { 'i', prefix = 'open', mode = { 'n' }, desc = 'open in [i]dea' },
  -- open_rider = { 'r', prefix = 'open', mode = { 'n' }, desc = 'open in [r]ider' },
  open_persistent_file_browser = { 'O', prefix = 'open', mode = { 'n' }, desc = 'persistent explorer' },
  search_config = { 'a', prefix = 'open', mode = { 'n' }, desc = 'search [a]ll configs' },
  empty_graphql_file = { 'G', prefix = 'open_new', mode = { 'n' }, desc = '[G]raphQL file' },
  empty_sql_file = { 'S', prefix = 'open_new', mode = { 'n' }, desc = '[S]QL file' },
  empty_bash_file = { 'b', prefix = 'open_new', mode = { 'n' }, desc = '[b]ash file' },
  empty_fish_file = { 'f', prefix = 'open_new', mode = { 'n' }, desc = '[f]sh file' },
  empty_go_file = { 'g', prefix = 'open_new', mode = { 'n' }, desc = '[g]o file' },
  empty_json_file = { 'j', prefix = 'open_new', mode = { 'n' }, desc = '[j]son file' },
  empty_lua_file = { 'l', prefix = 'open_new', mode = { 'n' }, desc = '[l]ua file' },
  empty_markdown_file = { 'm', prefix = 'open_new', mode = { 'n' }, desc = '[m]arkdown file' },
  empty_nushell_file = { 'u', prefix = 'open_new', mode = { 'n' }, desc = '[n]ushell file' },
  empty_python_file = { 'p', prefix = 'open_new', mode = { 'n' }, desc = '[p]ython file' },
  empty_sh_file = { 's', prefix = 'open_new', mode = { 'n' }, desc = '[s]h file' },
  empty_tsx_file = { 'x', prefix = 'open_new', mode = { 'n' }, desc = '[t]sx file' },
  empty_ts_file = { 't', prefix = 'open_new', mode = { 'n' }, desc = '[t]ypescript file' },
  empty_vim_file = { 'v', prefix = 'open_new', mode = { 'n' }, desc = '[v]im file' },
  empty_file = { 'n', prefix = 'open_new', mode = { 'n' }, desc = 'text file' },
  open_config_vim_modules = { 'M', prefix = 'open_vim', mode = { 'n' }, desc = 'explore nvim/[m]odules' },
  -- open_config_vim_context_browser = { 'C', prefix = 'open_vim', mode = { 'n' }, desc = 'explore ~/.[c]ontext/nvim' },
  search_vim_grep = { '/', prefix = 'open_vim', mode = { 'n' }, desc = 'grep nvim' },
  open_config_vim_autocmds = { 'a', prefix = 'open_vim', mode = { 'n' }, desc = 'open nvim/[a]utocmds.lua' },
  open_config_vim_init = { 'i', prefix = 'open_vim', mode = { 'n' }, desc = 'open nvim/[i]nit.lua' },
  open_config_vim_keymaps = { 'k', prefix = 'open_vim', mode = { 'n' }, desc = 'open nvim/[k]eymaps.lua' },
  open_config_vim_api = { '`', prefix = 'open_vim', mode = { 'n' }, desc = 'open nvim/api.lua' },
  search_vim_modules = { 'm', prefix = 'open_vim', mode = { 'n' }, desc = 'search nvim/[m]odules' },
  -- search_vim_context = { 'c', prefix = 'open_vim', mode = { 'n' }, desc = 'search ~/.[c]ontext/nvim' },
  qf_add = { 'a', prefix = 'quickfix', mode = { 'n' }, desc = 'quickfix [a]dd' },
  qf_clear = { 'c', prefix = 'quickfix', mode = { 'n' }, desc = 'quickfix [c]lear' },
  qf_delete = { 'd', prefix = 'quickfix', mode = { 'n' }, desc = 'quickfix [d]elete' },
  qf_focus = { 'f', prefix = 'quickfix', mode = { 'n' }, desc = 'quickfix [f]ocus' },
  qf_go = { 'g', prefix = 'quickfix', mode = { 'n' }, desc = 'quickfix [g]o' },
  qf_next = { 'n', prefix = 'quickfix', mode = { 'n' }, desc = 'quickfix [n]ext' },
  qf_open = { 'o', prefix = 'quickfix', mode = { 'n' }, desc = 'quickfix [o]pen' },
  qf_previous = { 'p', prefix = 'quickfix', mode = { 'n' }, desc = 'quickfix [p]revious' },
  qf_reverse = { 'r', prefix = 'quickfix', mode = { 'n' }, desc = 'quickfix [r]everse' },
  qf_all_diagnostics = { 'Z', prefix = 'quickfix', mode = { 'n' }, desc = 'quickfix all diagnostics' },
  qf_diagnostics = { 'z', prefix = 'quickfix', mode = { 'n' }, desc = 'quickfix diagnostics' },
  qf_close = { 'x', prefix = 'quickfix', mode = { 'n' }, desc = 'quickfix e[x]it' },
  qf_first = { '0', prefix = 'quickfix', mode = { 'n' }, desc = 'quickfix first' },
  qf_last = { '$', prefix = 'quickfix', mode = { 'n' }, desc = 'quickfix last' },
  qf_toggle = { 'q', prefix = 'quickfix', mode = { 'n' }, desc = 'quickfix toggle' },
  speed_dial_add = { 'a', prefix = 'speed_dial', mode = { 'n' }, desc = '[a]dd to speed dial' },
  speed_dial_clear = { 'c', prefix = 'speed_dial', mode = { 'n' }, desc = '[c]lear speed dial' },
  speed_dial_next = { 'n', prefix = 'speed_dial', mode = { 'n' }, desc = '[n]ext speed dial' },
  speed_dial_prev = { 'p', prefix = 'speed_dial', mode = { 'n' }, desc = '[p]revious speed dial' },
  speed_dial_select = { 's', prefix = 'speed_dial', mode = { 'n' }, desc = '[s]elect from speed dial' },
  terminal_1 = { '1', prefix = 'terminal', mode = { 'n' }, desc = 'terminal [1]' },
  terminal_2 = { '2', prefix = 'terminal', mode = { 'n' }, desc = 'terminal [2]' },
  terminal_3 = { '3', prefix = 'terminal', mode = { 'n' }, desc = 'terminal [3]' },
  terminal_4 = { '4', prefix = 'terminal', mode = { 'n' }, desc = 'terminal [4]' },
  terminal_5 = { '5', prefix = 'terminal', mode = { 'n' }, desc = 'terminal [5]' },
  terminal_add = { 'a', prefix = 'terminal', mode = { 'n' }, desc = 'terminal [a]dd' },
  terminal_bash_add = { 'b', prefix = 'terminal', mode = { 'n' }, desc = 'terminal [b]ash add' },
  terminal_cancel = { 'c', prefix = 'terminal', mode = { 'n' }, desc = 'terminal [c]ancel' },
  terminal_kill = { 'k', prefix = 'terminal', mode = { 'n' }, desc = 'terminal [k]ill' },
  -- terminal_list = { 'l', prefix = 'terminal', mode = { 'n' }, desc = 'terminal [l]ist' },
  terminal_nu_add = { 'n', prefix = 'terminal', mode = { 'n' }, desc = 'terminal [n]u add' },
  terminal_rename = { 'r', prefix = 'terminal', mode = { 'n' }, desc = 'terminal [r]ename' },
  terminal_bash_quickadd = { 'B', prefix = 'terminal', mode = { 'n' }, desc = 'terminal bash quickadd' },
  terminal_nu_quickadd = { 'N', prefix = 'terminal', mode = { 'n' }, desc = 'terminal nu quickadd' },
  terminal_quickadd = { ';', prefix = 'terminal', mode = { 'n' }, desc = 'terminal quickadd' },
  terminal_switch = { 't', prefix = 'terminal', mode = { 'n' }, desc = 'terminal switch' },
  terminal_execute_1 = { '1', prefix = 'terminal_execute', mode = { 'n' }, desc = 'terminal [1] execute' },
  terminal_execute_2 = { '2', prefix = 'terminal_execute', mode = { 'n' }, desc = 'terminal [2] execute' },
  terminal_execute_3 = { '3', prefix = 'terminal_execute', mode = { 'n' }, desc = 'terminal [3] execute' },
  terminal_execute_4 = { '4', prefix = 'terminal_execute', mode = { 'n' }, desc = 'terminal [4] execute' },
  terminal_execute_5 = { '5', prefix = 'terminal_execute', mode = { 'n' }, desc = 'terminal [5] execute' },
  terminal_execute_last = { 'e', prefix = 'terminal_execute', mode = { 'n' }, desc = 'terminal [e]xecute' },
  toggle_auto_comments = { 'a', prefix = 'vim', mode = { 'n' }, desc = '[A]uto-comment' },
  vim_spell_check = { 'S', prefix = 'vim', mode = { 'n' }, desc = '[S]pell check' },
  vim_eval = { 'e', prefix = 'vim', mode = { 'n' }, desc = '[e]val source' },
  vim_kill_buffers = { 'k', prefix = 'vim', mode = { 'n' }, desc = '[k]ill buffers' },
  vim_delete_buffer = { 'd', prefix = 'vim', mode = { 'n' }, desc = '[d]elete buffer' },
  vim_delete_file = { 'D', prefix = 'vim', mode = { 'n' }, desc = '[D]elete file' },
  vim_messages = { 'm', prefix = 'vim', mode = { 'n' }, desc = '[m]essages' },
  vim_number_line = { 'n', prefix = 'vim', mode = { 'n' }, desc = '[n]umber line' },
  vim_only_buffer = { 'o', prefix = 'vim', mode = { 'n' }, desc = '[o]nly buffer' },
  vim_previous_buffer = { 'p', prefix = 'vim', mode = { 'n' }, desc = '[p]revious buffer' },
  cant_close_vim = { 'q', prefix = 'vim', mode = { 'n' }, desc = '[q]uit vim' },
  vim_relative_number_line = { 'r', prefix = 'vim', mode = { 'n' }, desc = '[r]elative number line' },
  vim_signcolumn = { 's', prefix = 'vim', mode = { 'n' }, desc = '[s]igncolumn' },
  vim_wrap = { 'w', prefix = 'vim', mode = { 'n' }, desc = '[w]rap lines' },
  kill_tmux = { 'T', prefix = 'vim', mode = { 'n' }, desc = 'kill [t]mux' },
  exit_tmux = { 't', prefix = 'vim', mode = { 'n' }, desc = 'leave [t]mux' },
  search_color_schemes = { 'c', prefix = 'vim', mode = { 'n' }, desc = 'search [c]olor schemes' },
  vim_source = { 'v', prefix = 'vim', mode = { 'n' }, desc = 'source init.lua' },
  vim_tab_add = { 'a', prefix = 'vim_tabs', mode = { 'n' }, desc = 'tab [a]dd' },
  vim_tab_close = { 'c', prefix = 'vim_tabs', mode = { 'n' }, desc = 'tab [c]lose' },
  vim_tab_only = { 'o', prefix = 'vim_tabs', mode = { 'n' }, desc = 'tab [o]nly' },
  vim_tab_move_first = { 'H', prefix = 'vim_tabs', mode = { 'n' }, desc = 'tab move first' },
  vim_tab_move_last = { 'L', prefix = 'vim_tabs', mode = { 'n' }, desc = 'tab move last' },
  vim_tab_move_left = { 'h', prefix = 'vim_tabs', mode = { 'n' }, desc = 'tab move left' },
  vim_tab_move_right = { 'l', prefix = 'vim_tabs', mode = { 'n' }, desc = 'tab move right' },
  vim_tab_quickadd = { ';', prefix = 'vim_tabs', mode = { 'n' }, desc = 'tab quickadd' },
  vim_tab_name = { 'r', prefix = 'vim_tabs', mode = { 'n' }, desc = 'tab re[n]ame' },
  yank_filename = { 'f', prefix = 'yank', mode = { 'n' }, desc = '[f]ilename' },
}

